// Generated by CoffeeScript 1.3.1
(function() {

  exports.rtkey = "dnvvw8te9tsp4q94d2v48fuz";

  exports.nytkey = "02723ab94a02c8fd4f9f7c613d65778b:0:65487807";

  exports.yelp_consumer_key = "u75O1_PBhDnokFNF_mSqXQ";

  exports.yelp_consumer_secret = "_Izw_4AjCnKLhdOOcksJhdAQvpc";

  exports.yelp_oauth_token = "qAAd_MNlDka6JvpQXaUPUfH55wXkFCuS";

  exports.yelp_token_secret = "zZ4VPde4P6YX_BnZPVLMHhFZM2E";

}).call(this);
